# Generated by Django 4.2 on 2023-05-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchorread',
            options={'verbose_name_plural': 'Watch or Read'},
        ),
    ]
