# Generated by Django 4.2 on 2023-05-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_watchorread_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='watch_or_read',
            field=models.ForeignKey(default='Watch', on_delete=django.db.models.deletion.CASCADE, to='base.watchorread'),
        ),
    ]
